services:
  - type: web
    name: telegram-bot-adviser
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY  
        sync: false
      - key: GEMINI_MODEL
        value: gemini-2.0-flash-exp
      - key: AUDIO_PROCESSING_MODE
        value: gemini_direct
      - key: TRANSCRIPTION_MODE
        value: gemini_direct
      - key: MAX_CONTEXT_MESSAGES
        value: "10"
      - key: MESSAGE_LENGTH_LIMIT
        value: "4000" 